language: ruby
rvm:
- 2.1.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: W30J7oqS67BQIRwUJiPhdKW3J5X0WDkVHLhe9RFReE5nrEqKjOrsNoASl18gQBlFcLvHwQdt8U3WyO/m8YZqm9AvruX6r0kRMG1k4ocbpdFmZUOQy8+Jj/dl5X0q0Nxdhh4bnn3YkAki/vtLL70FuiDt+LyKkQ+ZKnxNbyT2aVw=
  - secure: kQoRit+oDRwq5kpHhEe5nwUagVrwA67Fkl5twJ377lzA9pUiILX44fqg+y6QbFNxGH5akldoFAtm+KGci9BMc3E11Qzs93u8Ar8Q78GXLF1wDfh4pROHDeQBziCYSWASMhTkOPpkO0dOe3lxcu4xvgChdSNfb6v+02QqlyrGkFw=
before_install:
- npm install -g bower
- bower install
- git config user.name "${GIT_NAME}"
- git config user.email "${GIT_EMAIL}"
install:
- bundle install
- npm install -g npm@2
- npm install && bower install
script: gulp build && htmlproof dist
after_success:
- gulp build:gh-pages
- cd ./gh-pages
- git init && git remote add deploy "https://${GH_TOKEN}@github.com/getroadmap/roadmap-site.git"
- git add .
- git commit -m "Development Build from ${TRAVIS_COMMIT}"
- git push -f deploy HEAD:gh-pages
- cd ../dist
- git init && git remote add deploy "https://${GH_TOKEN}@github.com/getroadmap/roadmap-site.git"
- git add .
- git commit -m "Production Build from ${TRAVIS_COMMIT}"
- git push -f deploy HEAD:dist
- "bundle exec cap production deploy"
branches:
  only:
  - master
