language: ruby
rvm:
- 2.1.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: gpyzcn9bQE6iUyRJTwqIpwjgvt3Bx/uy7BRUSDLjOiwN81J6NpSAq1nAAEQbd66bQoxgUxGH/ffNwho7PNQewOQVe0No0aonkoqpHrckkPMivndOFp/nCUd+PJwvLCNZCLVrQKAija5C7Dq3GNww5oOJ5q1AKpW53GYr+QhS8cg=
before_install:
- npm install -g bower
- bower install
- mkdir ./.travis
- openssl aes-256-cbc -K $encrypted_64cd943d900c_key -iv $encrypted_64cd943d900c_iv
  -in travis.enc -out .travis/deploy_key -d
- git config user.name ${GIT_NAME}
- git config user.email ${GIT_EMAIL}
install:
- bundle install
- bundle update
- npm install
- npm update
script: gulp build && htmlproof dist
after_success:
- gulp build:gh-pages
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- cd ./gh-pages
- git init && git remote add deploy https://${GH_TOKEN}@github.com/getroadmap/roadmap-site.git
- git add .
- git commit -m "Development Build from ${TRAVIS_COMMIT}"
- git push -f deploy HEAD:gh-pages
- cd ../dist
- git init && git remote add deploy https://${GH_TOKEN}@github.com/getroadmap/roadmap-site.git
- git add .
- git commit -m "Production Build from ${TRAVIS_COMMIT}"
- git push -f deploy HEAD:dist
branches:
  only:
  - master
