language: ruby
rvm:
- 2.1.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: W30J7oqS67BQIRwUJiPhdKW3J5X0WDkVHLhe9RFReE5nrEqKjOrsNoASl18gQBlFcLvHwQdt8U3WyO/m8YZqm9AvruX6r0kRMG1k4ocbpdFmZUOQy8+Jj/dl5X0q0Nxdhh4bnn3YkAki/vtLL70FuiDt+LyKkQ+ZKnxNbyT2aVw=
  - secure: R9WZ6skFYo86uQdSgUcxyKzHVT/M5lgYJaX5WfjsyvG6b3CrCcqHbj3tVw5uUnr3/+IISShyDdjmzUFaoVcVVHwJNAMC1UN4Gf6MSi7Qaw2/o38eP0qT+taAfaQzzztv4SFVa4cXE0/xE5JA0LVqMLFC3Lh09rRGm01zTiyFazI=
before_install:
- npm install -g bower
- bower install
- git config user.name "${GIT_NAME}"
- git config user.email "${GIT_EMAIL}"
- openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out
  config/deploy_id_rsa
- openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out
  config/deploy_id_rsa
- openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out
  ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent)"
- ssh-add
install:
- bundle install
- npm install -g npm@2
- npm install && bower install
script: gulp build && htmlproof dist
after_success:
- gulp build:gh-pages
- cd ./gh-pages
- git init && git remote add deploy "https://${GH_TOKEN}@github.com/getroadmap/roadmap-site.git"
- git add .
- git commit -m "Development Build from ${TRAVIS_COMMIT}"
- git push -f deploy HEAD:gh-pages
- cd ../dist
- git init && git remote add deploy "https://${GH_TOKEN}@github.com/getroadmap/roadmap-site.git"
- git add .
- git commit -m "Production Build from ${TRAVIS_COMMIT}"
- git push -f deploy HEAD:dist
- bundle exec cap production deploy
branches:
  only:
  - master
