language: ruby
rvm:
 - 2.1.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
before_install:
  - openssl aes-256-cbc -K $encrypted_64cd943d900c_key -iv $encrypted_64cd943d900c_iv -in travis.enc -out .travis/deploy_key -d
install: bundle install
script: bundle exec jekyll build && htmlproof ./.tmp
after_success:
  - chmod 600 .travis/deploy_key
  - ssh-add .travis/deploy_key
  - cd ./.tmp
  - git init && remote add deploy git@github.com:getroadmap/roadmap-site.git
  - git add .
  - git commit -m "Development Build from ${TRAVIS_COMMIT}"
  - git push deploy HEAD:gh-pages
