# App Settings
source: ./app/
destination: ./.tmp/


# Site settings
title: > #
  Roadmap - Intelligent Project Management, Scheduling, Time Tracking, and Resource Planning
description: > # this means to ignore newlines until "baseurl:"
  Manage your portfolio of projects with ease and intelligence.
  Visualize project plans, resource scheduling, and timesheets.
  Become a Project Management superstar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ppmroadmap.com" # the base hostname & protocol for your site

permalink: /news/:year/:month/:day/:title/


# Collections
collections:
  features:
    output: true
  customers:
    output: true
    permalink: /customers/:path/

email: support@ppmroadmap.com
twitter_username: ppmroadmap
github_username:  getroadmap

# Build settings
markdown: kramdown
exclude: ['styles', 'scripts', 'vendor', 'images']
