# App Settings
source: ./app/jekyll/
destination: ./.tmp/
# exclude: ['app/styles/*.scss']
environment: production


# Site settings
title: > #
  Roadmap - Intelligent Project Management, Scheduling, Time Tracking, and Resource Planning
description: > # this means to ignore newlines until "baseurl:"
  Manage your portfolio of projects with ease and intelligence.
  Visualize project plans, resource scheduling, and timesheets.
  Become a Project Management superstar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ppmroadmap.com" # the base hostname & protocol for your site

permalink: /news/:year/:month/:day/:title.html
excerpt_separator: <!--more-->

# Combine Periodicals
periodicals: []


# Collections
collections:
  features:
    output: true
  customers:
    output: true
    permalink: /customers/:path/
  blog:
    output: true
    permalink: /blog/:title.html


# Default Settings
defaults:
  -
    scope:
      path: ""
      type: customers   # <= here you can specify a collection now!
    values:
      layout: page
      class: _lo-customers
  -
    scope:
      path: ""
      type: posts   # <= here you can specify a collection now!
    values:
      layout: post
      class: _lo-posts

email: support@ppmroadmap.com
twitter_username: ppmroadmap
github_username:  getroadmap

# Build settings
markdown: kramdown

picture:
  source: "uploads/_fullsize"
  output: "generated"
  markup: "picture"


gems: ['jekyll/itafroma/archive']
archive:
  - path: /news/:year
    layout: archive_blog
    title: Blog archive — :year
    include:
      tags: ['PHP']
    exclude:
      categories: ['news']
      tags: ['drafts']
  - path: /news/:year/:month
    layout: archive_blog
    title: Blog archive — :month :year
    include:
      tags: ['PHP']
    exclude:
      categories: ['news']
      tags: ['drafts']
  - path: /news/:year/:month/:day
    layout: archive_blog
    title: Blog archive — :month :day, :year
    include:
      tags: ['PHP']
    exclude:
      categories: ['news']
      tags: ['drafts']
